---
title: "project2"
author: "Anh Nguyen"
date: '`r Sys.Date()`'
output: html_document
---

# Library

```{r}
# analysis
library(tidyverse)
library(car)
library(haven)
library(aods3)
library(vcd)
# residuals for glmm
library(DHARMa)
# fit glmm
library(glmmTMB)
# pretty table
library(sjPlot)
library(gtsummary)
library(labelled)
library(flextable)
library(webshot)
```

# Seed

```{r}
set.seed(3)
```

# Data

```{r}
df <- read_dta('publicrepfile.dta')
```

```{r}
df1 <- df |> 
  dplyr::select('GERMANE', 'prepost', 'VIEWS', 'TTID', 'treatment') |>
  drop_na() |>
  mutate_at(c('GERMANE', 'prepost', 'TTID', 'treatment'), 
            as.factor) |>
  filter(GERMANE == 1 | GERMANE == 2)
```

```{r}
var_label(df1) <- list(GERMANE = "Related to mental health theme",
                       prepost = "Pre or post treatment",
                       VIEWS = "Views",
                       TTID = "ID",
                       treatment = "Treatment group")
```

```{r}
df1 |>
  select(-TTID) |>
  tbl_summary(
    by = treatment,
    missing_text = "(Missing)",
    statistic = list(all_continuous() ~ "{mean} ± {sd}")
    ) |> 
  add_overall() %>%
  as_flex_table() %>% 
  save_as_image(path = "characteristic_table.png")
```

# EDA

## Univariate

```{r}
summary(df1)
```

```{r}
df1 %>% 
  select_if(is.numeric) %>%  
  gather(cols, value) %>%  
  ggplot(aes(x = value)) + 
  geom_boxplot() + 
  facet_grid(.~cols)
```

## Multivariate

```{r}
df1 %>%
  ggplot(aes(y=TTID, x=log(VIEWS+1))) +
  geom_boxplot() +
  facet_grid(treatment ~ .) +
  theme(
        axis.text.y=element_blank(),  #remove y axis labels
        axis.ticks.y=element_blank()  #remove y axis ticks
        )
```



# Question 1

## Fit

```{r}
m1 <- glmmTMB(VIEWS ~ treatment + (1|TTID) + prepost + GERMANE, data=df1, family=nbinom1)
summary(m1)
```

```{r}
gof(m1)
```


```{r}
m1 |>
  tbl_regression(
    exponentiate = TRUE,
    label = list(
      treatment ~ "Treatment group",
      prepost ~ "Pre or post treatment",
      GERMANE ~ "Related to mental health"
    ), 
    tidy_fun = function(...) broom.mixed::tidy(...)
  ) %>%
  as_flex_table() %>% 
  save_as_image(path = "association_table.png")
```

```{r}
tab_model(m1, file = "model.html")
webshot("model.html", "model.png")
```



## Diagnostics

```{r}
plot(m1)

plot(m1,IID~resid(.))
```


### Residuals plots

```{r}
simulationOutput <- simulateResiduals(fittedModel = m1, plot = F)
plot(simulationOutput)
```


```{r}
rootogram(df1$VIEWS, predict(m1))
```


### VIF

### Outliers

## Hypothesis test


```{r}
drop1(m1,test="Chisq")
```

```{r}
m2<-glmmTMB(VIEWS ~ (1|TTID) + prepost + GERMANE, data=df1, family=nbinom1)
anova(m2,m1)
```

```{r}
confint(m1)
```


# Package version 

```{r}
# export citation 
knitr::write_bib("packages.bib")
```


```{r}
sessionInfo()
```

